### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by ethanrasmussen** [ethanrasmussen/cyanea#1]
The following features are planned for implementation & will be checked off as they are completed:

- [ ]  Automatically retry failed connections
- [ ]  Automatically update proxy pool when all proxies have been used
- [ ]  Add additional proxy sources
- [ ]  Add documentation
